ALTER TABLE workers ADD COLUMN capabilities JSONB NULL;

ALTER TABLE workers DROP COLUMN CPUS;
ALTER TABLE workers DROP COLUMN RAM;
ALTER TABLE workers DROP COLUMN DISK;
ALTER TABLE workers DROP COLUMN GPU;
ALTER TABLE workers DROP COLUMN TAGS;
