-- Your SQL goes here
ALTER TABLE workers DROP COLUMN capabilities;

ALTER TABLE workers ADD COLUMN CPUS INTEGER NULL ;
ALTER TABLE workers ADD COLUMN RAM INTEGER NULL;
ALTER TABLE workers ADD COLUMN DISK DOUBLE PRECISION NULL;
ALTER TABLE workers ADD COLUMN GPU INTEGER NULL;
ALTER TABLE workers ADD COLUMN TAGS JSONB NULL;